### PR TITLE
Remove

### PR DESCRIPTION
**Pull request by kajatiger**

### CODE REVIEW

**Comment by jenni** [comment]
Hi Kaja I just tested this PR and the delete is not working. Can you tell me how you made it work to send the PR? thanks.

I paste the output from my console:

```
[24] pry(main)> trash = (google_files - keep).map(&:name)
=> ["discourse-2017-08-02-110102-v20170731030330.sql.gz",
 "discourse-2017-08-02-110228-v20170731030330.sql.gz",
 "discourse-2017-08-08-131114-v20170731030330.sql.gz",
 "discourse-2017-08-08-131137-v20170731030330.sql.gz",
 "discourse-2017-08-08-131237-v20170731030330.sql.gz",
 "discourse-2017-08-02-105913-v20170731030330.sql.gz",
 "discourse-2017-08-02-103046-v20170731030330.tar.gz",
 "discourse-2017-08-02-110102-v20170731030330.sql.gz",
 "discourse-2017-08-02-105913-v20170731030330.sql.gz",
 "discourse-2017-08-02-110228-v20170731030330.sql.gz",
 "discourse-2017-08-08-131114-v20170731030330.sql.gz",
 "discourse-2017-08-02-110102-v20170731030330.sql.gz"]
[25] pry(main)> trash.each { |d| d.delete(true) }
TypeError: no implicit conversion of true into String
from (pry):25:in `delete'
[26] pry(main)>
```

Your code is basically using the **delete method from Ruby** because you are not specifying the session to refer to the delete instance method of google_drive gem. 

Please check the documentation in Ruby-doc:

https://ruby-doc.org/core-2.2.0/Array.html#method-i-delete

Your .delete without referring to session is expecting an **string** as an argument. Not a boolean. The delete instance method of **google_drive is expecting a boolean**. 

Why did you send this PR versus the PR I've sent earlier this morning in which the code is working as expected?

```
trash.each {|f| session.collection_by_title(folder_name).file_by_title(f).delete(permanent = true)}
output is a bunch of HTTP requests and
=> ["discourse-2017-08-02-110102-v20170731030330.sql.gz",
 "discourse-2017-08-02-110228-v20170731030330.sql.gz",
 "discourse-2017-08-08-131114-v20170731030330.sql.gz",
 "discourse-2017-08-08-131137-v20170731030330.sql.gz",
 "discourse-2017-08-08-131237-v20170731030330.sql.gz",
 "discourse-2017-08-02-105913-v20170731030330.sql.gz",
 "discourse-2017-08-02-103046-v20170731030330.tar.gz",
 "discourse-2017-08-02-110102-v20170731030330.sql.gz",
 "discourse-2017-08-02-105913-v20170731030330.sql.gz",
 "discourse-2017-08-02-110228-v20170731030330.sql.gz",
 "discourse-2017-08-08-131114-v20170731030330.sql.gz",
 "discourse-2017-08-02-110102-v20170731030330.sql.gz"]
and
[27] pry(main)> session.collection_by_title(folder_name).files.count
=> 5
```

**Review by jenni — CHANGES_REQUESTED** [review]
comments in the PR

**Review by jenni — APPROVED** [review]
woohoooooo

**Comment by rstammer** [comment]
👍  👏

**Pull request merged**
